
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
  
frontend:
  themes: !include_dir_merge_named themes
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

mqtt:
  broker: 192.168.7.147
  
speedtestdotnet:
  scan_interval:
    hours: 12
  monitored_conditions:
    - ping
    - download
    - upload
