
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
  
frontend:
  themes: !include_dir_merge_named themes
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
sensor: !include sensors.yaml


#sensor: 
#  - platform: systemmonitor
#    resources:
#      - type: disk_use_percent
#        arg: /config
#      - type: memory_use
#      - type: processor_use
#      - type: processor_temperature
#      - type: last_boot
