
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
  
frontend:
  themes: !include_dir_merge_named themes
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

# Sensors
sensor: 
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      
  - platform: scrape
    resource: !secret tsa_wait_url
    select: !secret tsa_wait_selector
    name: TSA Wait Time
    
  - platform: moon
  
  - platform: season
    type: astronomical
    
  - platform: template
    sensors:
      speedtest_last_updated:
        friendly_name: "Last Updated"
        value_template: "{{ as_timestamp(states.sensor.speedtest_download.last_updated) | timestamp_custom('%I:%M %p %Z') }}"  
    
speedtestdotnet:
  scan_interval: '00:30:00'
  monitored_conditions:
    - ping
    - download
    - upload
