- platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      
- platform: scrape
  resource: !secret.tsa_wait_url
  select: !secrets.tsa_wait_selector
  name: TSA Wait Time
