#Home Assistant and Server
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /config
  - type: memory_use
  - type: processor_use
  - type: processor_temperature
  - type: last_boot
  - type: network_in
    arg: wlp0s20f3
  - type: network_out
    arg: wlp0s20f3
  - type: ipv4_address
    arg: wlp0s20f3
  - type: throughput_network_in
    arg: wlp0s20f3
  - type: throughput_network_out
    arg: wlp0s20f3
  
  
- platform: uptime
  name: HA Uptime
  unit_of_measurement: minutes
- platform: version
  source: hassio  

- platform: template
  sensors:
    speedtest_last_updated:
      friendly_name: "Last Updated"
      value_template: "{{ as_timestamp(states.sensor.speedtest_download.last_updated) | timestamp_custom('%I:%M %p %Z') }}"  

# TSA Wait Time
- platform: scrape
  resource: !secret tsa_wait_url
  select: !secret tsa_wait_selector
  name: TSA Wait Time

# Weather
- platform: moon

- platform: season
  type: astronomical


#Motion Sensor Battery Levels
- platform: template
  sensors:
    bedroom_motion_battery:
      friendly_name: "Bedroom Motion Sensor Battery"
      value_template: "{{ state_attr('binary_sensor.bedroom_sensor_motion', 'battery_level') | int }}"
    kitchen_motion_battery:
      friendly_name: "Kitchen Motion Sensor Battery"
      value_template: "{{ state_attr('binary_sensor.kitchen_sensor_motion', 'battery_level') | int }}"
    studio_motion_battery:
      friendly_name: "Studio Motion Sensor Battery"
      value_template: "{{ state_attr('binary_sensor.my_office_sensor_motion', 'battery_level') | int }}"
    bedroom_last_motion:
      friendly_name: 'Bedroom Last Motion'
      value_template: "{{ (states.binary_sensor.bedroom_sensor_motion.last_changed).isoformat() }}"
      device_class: timestamp
    kitchen_last_motion:
      friendly_name: 'Kitchen Last Motion'
      value_template: "{{ (states.binary_sensor.kitchen_sensor_motion.last_changed).isoformat() }}"
      device_class: timestamp      
    studio_last_motion:
      friendly_name: 'Studio Last Motion'
      value_template: "{{ (states.binary_sensor.my_office_sensor_motion.last_changed).isoformat() }}"
      device_class: timestamp      


  
